import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Blog from '../components/Blog'

const env = process.env.STRAPIBASEURL; 

export async function getStaticProps(context) {
  const fetchParams = {
    method: "POST", 
    headers: { 
      "content-type": "application/json"

    },
    body: JSON.stringify(
      {
        query: `
        {
          blogPosts{
            title
            description
            blogBody
            slug
          }
        }
        `
      }
    )
  }
  const res = await fetch(`${env}/graphql`, fetchParams); 
  const {data} = await res.json(); 
  return {
    props: data
  };
}

export default function Home({blogPosts}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {blogPosts.map((blog, i)=>{
            const {title, description, slug} = blog
            return <Blog title={title} description={description} slug={slug} key={i}/>
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
