import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Blog from '../components/Blog'
import Footer from '../components/Footer'
const URL = process.env.STRAPIBASEURL; 

export async function getStaticProps(context) {
  const fetchParams = {
    method: "POST", 
    headers: { 
      "content-type": "application/json"

    },
    body: JSON.stringify(
      {
        query: `
        {
          blogPosts{
            title
            description
            blogBody
            slug
          }
        }
        `
      }
    )
  }
  const res = await fetch(`${URL}/graphql`, fetchParams); 
  const {data} = await res.json(); 
  return {
    props: data
  };
}

export default function Home({blogPosts}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {blogPosts.map((blog, i)=>{
            const {title, description, slug, blogBody} = blog
            return <Blog title={title} description={description} slug={slug}key={i}/>
          })}
        </div>
        <Footer/>
      </main>
    </div>
  )
}
